spring:
  application:
    name: ryyppy.net
  datasource:
    url: jdbc:postgresql://localhost/ryyppynet
    username: ryyppynet
    password: ryyppynet
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  session:
    timeout: 90d
    jdbc:
      initialize-schema: always
      cleanup-cron: "0 */15 * * * *"
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  messages:
    basename: messages,drinkcounter.version
  docker:
    compose:
      file: docker/docker-compose.yml

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 6115241938-fkfn0jc12l66aelicc3v19so1e9gl58o.apps.googleusercontent.com
            client-secret: REPLACE_THIS

application:
  version: "@project.version@"

google:
  auth:
    enabled: false  # Set to true or use GOOGLE_AUTH_ENABLED=true environment variable to enable Google authentication