spring:
  application:
    name: ryyppy.net
  datasource:
    url: jdbc:postgresql://localhost/ryyppynet
    username: ryyppynet
    password: ryyppynet
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  session:
    timeout: 90d
    jdbc:
      initialize-schema: always
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  messages:
    basename: messages,drinkcounter.version
  docker:
    compose:
      file: docker/docker-compose.yml

application:
  version: "@project.version@"