spring:
  application:
    name: ryyppy.net
  datasource:
    url: jdbc:postgresql://localhost/ryyppynet
    username: ryyppynet
    password: ryyppynet
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  session:
    timeout: 90d
    jdbc:
      initialize-schema: always
      cleanup-cron: "0 */15 * * * *"
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  messages:
    basename: messages,drinkcounter.version
  docker:
    compose:
      file: docker/docker-compose.yml

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:REPLACE_THIS}
            client-secret: ${GOOGLE_CLIENT_SECRET:REPLACE_THIS}

application:
  version: "@project.version@"